<form method="post">
  <h2>Questions</h2>
  <div class="row">
    {{ foreach $questions as $question }}
      <div class="col-md-6 mb-3">
        <label for="native_phrase{{$question['id']}}" class="form-label">Native Phrase</label>
        <input type="text" class="form-control" id="native_phrase{{$question['id']}}" name="questions[{{$question['id']}}][native_phrase]" value="{{$question['native_phrase']}}" required>
      </div>
      <div class="col-md-6 mb-3">
        <label for="foreign_phrase{{$question['id']}}" class="form-label">Foreign Phrase</label>
        <input type="text" class="form-control" id="foreign_phrase{{$question['id']}}" name="questions[{{$question['id']}}][foreign_phrase]" value="{{$question['foreign_phrase']}}" required>
      </div>

      <div class="col-md-6 mb-3">
        <label for="alternative_native_phrases{{$question['id']}}" class="form-label">Alternative Native Phrases</label>
        <textarea class="form-control" id="alternative_native_phrases{{$question['id']}}" name="questions[{{$question['id']}}][alternative_native_phrases]">{{$question['alternative_native_phrases']}}</textarea>
      </div>

      <div class="col-md-6 mb-3">
        <label for="alternative_foreign_phrases{{$question['id']}}" class="form-label">Alternative Foreign Phrases</label>
        <textarea class="form-control" id="alternative_foreign_phrases{{$question['id']}}" name="questions[{{$question['id']}}][alternative_foreign_phrases]">{{$question['alternative_foreign_phrases']}}</textarea>
      </div>
    {{ /foreach }}
  </div>
  
  <button class="btn btn-primary" type="submit">Submit</button>
</form>


Make a view based on fat free framework's template engine.
The view will iterate an array of questions.
In the view is a form where from the questions array is a question called native_phrase and answer called foreign_phrase.
The user should be able to edit both native_phrase and foreign_phrase. 
The user should also be able to add a series of alternative phrases to native_phrase and foreign_phrase. This can be done from a text area - one textarea for alternative native_phrase and another textarea for alternative foreign_phrase.
The user should be able to submit each iteration of the fields generated by the questions array.

question
  teaching_phrase 
  learning_phrase
  FK_lesson_id

alternative_learning_phrase
  learning_phrase
  FK_question_id

alternative_teaching_phrase
  teaching_phrase
  FK_question_id

---

Write the following sqlite schema along with primary and foreign key linking. 

Courses table with columns title, language, slug, and version, have many lessons. 
Lessons table with columns title, slug, and tutorial, have many sentences.
Sentences table links the tables native_sentences and foreign_sentences to lessons.
Native_sentences table has the column sentence. 
Foreign_sentences table has the column sentence. 


courses [title, language, slug, version]
	have_many
	lessons [title, slug, tutorial]
		have_many
		sentences [(links native_sentences and foreign_sentences to lessons)]
			have_many
			native_sentences [sentence]
			foreign_sentences [sentence]

  {
    "inProduction": true,
    "_id": "5de6647978e18605844b28e3",
    "slug": "verb-chaining",
    "title": "Verb chaining",
    "tutorial": "Verb chains or verb chaining...",
    "lang": "Finnish",
    "questions": [
      {
        "nativeLang": [
          "We plan to travel on holiday to Italy",
          "We intend to travel on holiday to Italy",
          "We plan to travel to Italy on holiday",
          "We intend to travel to Italy on holiday"
        ],
        "foreignLang": [
          "Aiomme matkustaa lomalla Italiaan"
        ],
        "_id": "5e088efcb2c71417603a7b34"
      }
    ],
    "__v": 5
  }